/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.agary.hrmapp;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author arthathagary
 */
public class HrManagerPage extends javax.swing.JFrame {

    /**
     * Creates new form HrManagerPage
     */
    HrManager hrMnr = new HrManager();
    Employee emp = new Employee();
    FileManagement fileM = new FileManagement();

    private void initiateEmployees() {
        try {
            try (FileReader fileReader = new FileReader("/Users/arthathagary/Documents/ICBT Docs/Assesments/HrmAppTxtFiles/departmentDetails.txt")) {
                BufferedReader bufferedReader = new BufferedReader(fileReader);
                FileReader fileReader2 = new FileReader("/Users/arthathagary/Documents/ICBT Docs/Assesments/HrmAppTxtFiles/designationDetails.txt");
                BufferedReader bufferedReader2 = new BufferedReader(fileReader2);
                String line, line2, deptName, desigName;
                while ((line = bufferedReader.readLine()) != null) {
                    deptName = line.split(" ")[1];
                    cmbDepartment.addItem(deptName);
                    cmbDeleteDep.addItem(deptName);
                }
                bufferedReader.close();
                while ((line2 = bufferedReader2.readLine()) != null) {
                    desigName = line2.split(" ")[1];
                    cmbDesignation.addItem(desigName);
                    cmbDeleteDesignation.addItem(desigName);
                }
                bufferedReader2.close();
                fileReader2.close();
            }
        } catch (FileNotFoundException ex) {
            System.err.println(ex);
        } catch (IOException ex) {
            System.err.println(ex);
        }

    }

    public HrManagerPage() {
        initComponents();
        initiateEmployees();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEpfNumber = new javax.swing.JTextField();
        txtEmployeeName = new javax.swing.JTextField();
        cmbDepartment = new javax.swing.JComboBox<>();
        cmbDesignation = new javax.swing.JComboBox<>();
        btnAddEmployee = new javax.swing.JButton();
        btnSearchEmployee = new javax.swing.JButton();
        btnDeleteEmployee = new javax.swing.JButton();
        btnViewEmployeeDetails = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnDeleteDepartment = new javax.swing.JButton();
        cmbDeleteDep = new javax.swing.JComboBox<>();
        btnDeleteDesignation = new javax.swing.JButton();
        cmbDeleteDesignation = new javax.swing.JComboBox<>();
        btnAddDesignation = new javax.swing.JButton();
        btnAddDepartment = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 550));

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel1.setText("EPF Number");

        jLabel2.setText("Employee Name");

        jLabel4.setText("Department");

        jLabel5.setText("Designation");

        cmbDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDepartmentActionPerformed(evt);
            }
        });

        btnAddEmployee.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnAddEmployee.setText("Add Employee");
        btnAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmployeeActionPerformed(evt);
            }
        });

        btnSearchEmployee.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnSearchEmployee.setText("Search Employee");
        btnSearchEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchEmployeeActionPerformed(evt);
            }
        });

        btnDeleteEmployee.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnDeleteEmployee.setText("Delete Employee");
        btnDeleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEmployeeActionPerformed(evt);
            }
        });

        btnViewEmployeeDetails.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnViewEmployeeDetails.setText("View Employee Details");
        btnViewEmployeeDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEmployeeDetailsActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));

        btnDeleteDepartment.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnDeleteDepartment.setText("Delete Department");
        btnDeleteDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDepartmentActionPerformed(evt);
            }
        });

        btnDeleteDesignation.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnDeleteDesignation.setText("Delete Designation");
        btnDeleteDesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDesignationActionPerformed(evt);
            }
        });

        btnAddDesignation.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnAddDesignation.setText("Add Designation");
        btnAddDesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDesignationActionPerformed(evt);
            }
        });

        btnAddDepartment.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnAddDepartment.setText("Add Depatment");
        btnAddDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDepartmentActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbDeleteDep, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDeleteDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDeleteDepartment)
                            .addComponent(btnDeleteDesignation))))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteDepartment)
                    .addComponent(cmbDeleteDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddDepartment))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteDesignation)
                    .addComponent(cmbDeleteDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddDesignation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnBack))
                .addGap(16, 16, 16))
        );

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setText("Manage Employees Details");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setText("Manage Departments And Designations");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(125, 125, 125))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEpfNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDeleteEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSearchEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnViewEmployeeDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel3)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtEpfNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(cmbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(cmbDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAddEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewEmployeeDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDepartmentActionPerformed
        // TODO add your handling code here:
        String depNo = JOptionPane.showInputDialog("Enter Department Number");

        String depName = JOptionPane.showInputDialog("Enter Department Name");
        boolean valid = true;
        if (depNo.isEmpty() || depName.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Any field can't be empty", "Register Form", JOptionPane.ERROR_MESSAGE);
            valid = false;
        }else{
        if (valid && fileM.checkAvailability("/Users/arthathagary/Documents/ICBT Docs/Assesments/HrmAppTxtFiles/departmentDetails.txt",depNo) == false) {

            cmbDepartment.addItem(depName);
            cmbDeleteDep.addItem(depName);

            int depNoinInt = Integer.parseInt(depNo);
            ArrayList<Department> departments = hrMnr.addDepartment(depNoinInt, depName);
            Department.writeFile(departments, "/Users/arthathagary/Documents/ICBT Docs/Assesments/HrmAppTxtFiles/departmentDetails.txt");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Dep Num already available in the file use another number");
        }
        }


    }//GEN-LAST:event_btnAddDepartmentActionPerformed

    private void btnAddDesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDesignationActionPerformed
        // TODO add your handling code here:
        String desiNo = JOptionPane.showInputDialog("Enter Designation Number");

        String desiName = JOptionPane.showInputDialog("Enter Designationt Name");
        boolean valid = true;
        if (desiNo.trim().isEmpty() || desiName.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Any field can't be empty", "Register Form", JOptionPane.ERROR_MESSAGE);
            valid = false;
        }else{
        if (valid && fileM.checkAvailability("/Users/arthathagary/Documents/ICBT Docs/Assesments/HrmAppTxtFiles/designationDetails.txt", desiNo) == false) {

            cmbDesignation.addItem(desiName);
            cmbDeleteDesignation.addItem(desiName);

            int desiNoinInt = Integer.parseInt(desiNo);
            ArrayList<Designation> designations = hrMnr.addDesignation(desiNoinInt, desiName);
            Designation.writeFile(designations, "/Users/arthathagary/Documents/ICBT Docs/Assesments/HrmAppTxtFiles/designationDetails.txt");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Designation Num already available in the file use another number");
        }
        }

    }//GEN-LAST:event_btnAddDesignationActionPerformed

    private void btnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmployeeActionPerformed
        // TODO add your handling code here:
        boolean valid = true;
        if (txtEpfNumber.getText().isEmpty() || txtEmployeeName.getText().isEmpty() || cmbDepartment.getSelectedItem().toString().isEmpty() || cmbDesignation.getSelectedItem().toString().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Field can't be black", "Error in Adding Employee", JOptionPane.ERROR_MESSAGE);
            valid = false;
        }else{
        if (valid && checkAvailabilityEmp() == false) {
            String epfNo = txtEpfNumber.getText();
            int epfNoinInt = Integer.parseInt(epfNo);
            String epfName = txtEmployeeName.getText();
            String depName = cmbDepartment.getSelectedItem().toString();
            String desigName = cmbDesignation.getSelectedItem().toString();

            ArrayList<Employee> employees = hrMnr.addEmployee(epfNoinInt, epfName, depName, desigName);
            Employee.writeFile(employees, "/Users/arthathagary/Documents/ICBT Docs/Assesments/HrmAppTxtFiles/employeesDetails.txt");
            JOptionPane.showMessageDialog(rootPane, "Succesfully wrote employee details to the file");
        } else {
            JOptionPane.showMessageDialog(rootPane, "EPF Number already available");
        }
        }
    }//GEN-LAST:event_btnAddEmployeeActionPerformed
    public boolean checkAvailabilityEmp() {
        FileManagement obj = new FileManagement();
        String getInput = txtEpfNumber.getText();
        boolean returnValue = obj.checkAvailability("/Users/arthathagary/Documents/ICBT Docs/Assesments/HrmAppTxtFiles/employeesDetails.txt", getInput);
        return returnValue;
    }

    private void cmbDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDepartmentActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_cmbDepartmentActionPerformed

    private void btnDeleteDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDepartmentActionPerformed
        // TODO add your handling code here:
        String delDep = cmbDeleteDep.getSelectedItem().toString();
        cmbDeleteDep.removeItem(delDep);
        cmbDepartment.removeItem(delDep);
        hrMnr.deleteDepartment("/Users/arthathagary/Documents/ICBT Docs/Assesments/HrmAppTxtFiles/departmentDetails.txt", delDep);
        JOptionPane.showMessageDialog(rootPane, "Succesfully Delete The Department");

    }//GEN-LAST:event_btnDeleteDepartmentActionPerformed

    private void btnDeleteDesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDesignationActionPerformed
        // TODO add your handling code here:
        String delDesi = cmbDeleteDesignation.getSelectedItem().toString();
        cmbDeleteDesignation.removeItem(delDesi);
        cmbDesignation.removeItem(delDesi);
        hrMnr.deleteDesignation("/Users/arthathagary/Documents/ICBT Docs/Assesments/HrmAppTxtFiles/designationDetails.txt", delDesi);
        JOptionPane.showMessageDialog(rootPane, "Succesfully Delete The Designation");


    }//GEN-LAST:event_btnDeleteDesignationActionPerformed

    private void btnDeleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEmployeeActionPerformed
        // TODO add your handling code here:
        ArrayList<String> wholeDep = emp.getWholeEpfNum();
        String empEpfNo = JOptionPane.showInputDialog("Enter Employee EPF Number");
        if (wholeDep.contains(empEpfNo)) {
            hrMnr.deleteEmployee("/Users/arthathagary/Documents/ICBT Docs/Assesments/HrmAppTxtFiles/employeesDetails.txt", empEpfNo);
            JOptionPane.showMessageDialog(rootPane, "Succesfully Delete The Employee Details");
        } else if (empEpfNo.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "EPF Number can't be blank");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Epf Number does't available");
        }
    }//GEN-LAST:event_btnDeleteEmployeeActionPerformed

    private void btnViewEmployeeDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEmployeeDetailsActionPerformed
        // TODO add your handling code here:
        HrManager hrM = new HrManager("Hr Manager");
    }//GEN-LAST:event_btnViewEmployeeDetailsActionPerformed

    private void btnSearchEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchEmployeeActionPerformed
        // TODO add your handling code here:
        Object[] options = {"EPF No", "Name", "Department", "Designation"};
        int x = JOptionPane.showOptionDialog(null, "Select a option to search employee details",
                "Search Employees Details",
                JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE, null, options, options[0]);

        if (x != -1) {
            System.err.println("hello" + options[x]);
            if (options[x].equals("Name")) {
                String empName = JOptionPane.showInputDialog("Enter Employee Name to get details");
                emp.showEmployeeDetails(empName);
            } else if (options[x].equals("EPF No")) {
                String empNumber = JOptionPane.showInputDialog("Enter Employee EPF Number to get details");
                emp.showEmployeeDetails(empNumber);
            } else if (options[x].equals("Department")) {
                String Dept = JOptionPane.showInputDialog("Enter Employee Departmrnt to get details");
                emp.showEmployeeDetails(Dept);
            } else if (options[x].equals("Designation")) {
                String desig = JOptionPane.showInputDialog("Enter Employee Designation to get details");
                emp.showEmployeeDetails(desig);
            }
        }


    }//GEN-LAST:event_btnSearchEmployeeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        LoginPage obj = new LoginPage();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HrManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HrManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HrManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HrManagerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HrManagerPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDepartment;
    private javax.swing.JButton btnAddDesignation;
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteDepartment;
    private javax.swing.JButton btnDeleteDesignation;
    private javax.swing.JButton btnDeleteEmployee;
    private javax.swing.JButton btnSearchEmployee;
    private javax.swing.JButton btnViewEmployeeDetails;
    private javax.swing.JComboBox<String> cmbDeleteDep;
    private javax.swing.JComboBox<String> cmbDeleteDesignation;
    private javax.swing.JComboBox<String> cmbDepartment;
    private javax.swing.JComboBox<String> cmbDesignation;
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtEmployeeName;
    private javax.swing.JTextField txtEpfNumber;
    // End of variables declaration//GEN-END:variables
}
